name: centrkrasok
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  http: ^0.13.6
  shared_preferences: 2.2.2
  html_unescape: ^2.0.0
  flutter_svg: ^2.0.0
  connectivity_plus: ^6.0.0
  path: ^1.9.0
  sqflite: ^2.3.3
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.3.1
  mobile_scanner: ^5.2.3
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
